scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.70.137.169:9090']

  - job_name: 'backend-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['10.70.137.169:8080']
        labels:
          group: 'development'