--insert menu--
INSERT INTO db_backend_service.permissions (id, created_at, description, end_point, glyphicon, is_api, modified_at, name, parent_id, permission_level) VALUES(1, '2024-11-04 00:00:00', 'Home is first page', '/app/home', 'home', 0, NULL, 'Home', NULL, 1);
INSERT INTO db_backend_service.permissions (id, created_at, description, end_point, glyphicon, is_api, modified_at, name, parent_id, permission_level) VALUES(2, '2024-11-04 00:00:00', 'Management Account is page to management account and roles', '/app/management-account/data-account', 'user', 0, NULL, 'Accounts', NULL, 1);
INSERT INTO db_backend_service.permissions (id, created_at, description, end_point, glyphicon, is_api, modified_at, name, parent_id, permission_level) VALUES(3, '2024-11-04 00:00:00', 'Management Product is page to management product and category', '/app/management-product/data-product', 'database', 0, NULL, 'Products', NULL, 1);
INSERT INTO db_backend_service.permissions (id, created_at, description, end_point, glyphicon, is_api, modified_at, name, parent_id, permission_level) VALUES(4, '2024-11-04 00:00:00', 'Management Transaction is page to management transaction and report', '/app/management-transaction', 'money-bill', 0, NULL, 'Transaction', NULL, 1);
INSERT INTO db_backend_service.permissions (id, created_at, description, end_point, glyphicon, is_api, modified_at, name, parent_id, permission_level) VALUES(5, '2024-11-04 00:00:00', 'Account is page to show data account and create new or update account', '/app/management-account/data-account', 'cog', 0, NULL, 'Data Account', 2, 2);
INSERT INTO db_backend_service.permissions (id, created_at, description, end_point, glyphicon, is_api, modified_at, name, parent_id, permission_level) VALUES(6, '2024-11-04 00:00:00', 'Roles is page to show data roles and create new or update roles', '/app/management-account/settings-roles', 'cog', 0, NULL, 'Settings Roles', 2, 2);
INSERT INTO db_backend_service.permissions (id, created_at, description, end_point, glyphicon, is_api, modified_at, name, parent_id, permission_level) VALUES(7, '2024-11-04 00:00:00', 'Permissions is page to show data permissions and create new or update permissions', '/app/management-account/data-permissions', 'cog', 0, NULL, 'Data Permissions', 2, 2);
INSERT INTO db_backend_service.permissions (id, created_at, description, end_point, glyphicon, is_api, modified_at, name, parent_id, permission_level) VALUES(8, '2024-11-04 00:00:00', 'Product is page to show data product and create new or update product', '/app/management-product/data-product', 'cog', 0, NULL, 'Data Product', 3, 2);
INSERT INTO db_backend_service.permissions (id, created_at, description, end_point, glyphicon, is_api, modified_at, name, parent_id, permission_level) VALUES(9, '2024-11-04 00:00:00', 'Category is page to show data category and create new or update category', '/app/management-product/data-category', 'cog', 0, NULL, 'Data Category', 3, 2);
INSERT INTO db_backend_service.permissions (id, created_at, description, end_point, glyphicon, is_api, modified_at, name, parent_id, permission_level) VALUES(10, '2024-11-04 00:00:00', 'Roles is page to show data roles and update permissions', '/app/management-account/data-roles', 'cog', 0, NULL, 'Data Roles', 2, 2);