apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-service-config
data:
  application.yml: |
    spring:
      rabbitmq:
        host: 192.168.5.91
        port: 5672
        stream:
          username: guest
          password: guest
      datasource:
        url: jdbc:mysql://192.168.5.91:3306/db_backend_service?allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: rootroot
        driver-class-name: com.mysql.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
      data:
        redis:
          host: localhost
          port: 6379
    server:
      port: 8080
      servlet:
        context-path: /backend-service
    jwt:
      secret-key: 7f312164792f0ab848c987b7e0980807faddf42cc19d284e0822ce40888a30b59f4701bee6574a7eacdc8d6498f970462b25db28c512e8a6bbf218deb6294db5
      expiration: 86400000
    sentry:
      dsn: https://5a3928796fbc6ef7ff1acf1479fb393b@o4505036091359232.ingest.us.sentry.io/4508243027886080
    management:
      endpoint:
        metrics:
          enabled: true
        prometheus:
          enabled: true
      endpoints:
        web:
          exposure:
            include: '*'

